baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Hugo Site"

# Multilingual routing: put default language in a subdirectory (e.g. /en/)
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[params]

[languages]
  [languages.en]
    languageName = "English"
    lang = "en"
    languageCode = "en-us"
    weight = 1
  [languages.fa]
    languageName = "Farsi"
    lang = "fa"
    languageCode = "fa"
    weight = 2
    languageDirection = "rtl"
  [languages.fr]
    languageName = "Français"
    lang = "fr"
    languageCode = "fr"
    weight = 3
  [languages.ja]
    languageName = "日本語"
    lang = "ja"
    languageCode = "ja"
    weight = 4