name = 'H'
license = 'MIT'
licenselink = 'https://github.com/mahdiarsadeghi/H/LICENSE'
description = 'minimal blog'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/mahdiarsadeghi/H'

# If you have a running demo of the theme
demosite = 'https://mahdiarsadeghi.github.io/H'

# Taxonomy terms
tags = ['blog']
features = ['minimal']

# If the theme has a single author
[author]
  name = 'mahdiar'
  homepage = 'mahdiar.org'
